#requires -Version 5.1
<#
.SYNOPSIS
    Regenerates .claude/skills/layer-*/SKILL.md frontmatter from bindings.yaml + layers/.
.DESCRIPTION
    Frontmatter (allowed-tools, shell, disable-model-invocation, description) is derived.
    Skill BODY is hand-authored and preserved across regenerations.

    The script:
      1. Reads infrastructure/agent/skills.yaml for the canonical skill list.
      2. For each skill with a layer_id, reads layers/<id>/layer.md to get the
         "Bindings used" list, resolves capabilities to tool names from bindings.yaml,
         and produces an allowed-tools list.
      3. Replaces the YAML frontmatter at the top of each SKILL.md, leaving the
         body untouched.
.EXAMPLE
    pwsh ./scripts/generate-skills.ps1
#>
[CmdletBinding()]
param(
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$here = $PSScriptRoot

Import-Module (Join-Path $here "lib\Read-Bindings.ps1") -Force

$bindings = Read-Bindings
$skillsDoc = Read-InfraYaml -RelativePath "infrastructure/agent/skills.yaml"

$repoRoot   = Split-Path $here -Parent
$skillsRoot = Join-Path $repoRoot ".claude\skills"

foreach ($s in $skillsDoc.skills) {
    $skillDir = Join-Path $skillsRoot $s.name
    $skillFile = Join-Path $skillDir "SKILL.md"
    if (-not (Test-Path $skillFile)) {
        Write-Warning "skill file missing, skipping: $skillFile"
        continue
    }

    # Default allowed-tools (every layer needs file IO + shell)
    $allowed = @("Read", "Write", "Edit", "Glob", "Grep", "Bash")

    # If this is a layer skill, harvest "Bindings used" from layer.md (cosmetic for now;
    # MCP tool names get added by Phase 6 enhancement).
    if ($s.layer_id) {
        $layerMd = Join-Path $repoRoot "layers\$($s.layer_id)\layer.md"
        if (Test-Path $layerMd) {
            $body = Get-Content $layerMd -Raw
            if ($body -match '## Bindings used\s*\r?\n\s*\r?\n(?<list>(?:- [^\r\n]+\r?\n)+)') {
                $items = $Matches['list'] -split "`n" | ForEach-Object {
                    if ($_ -match '^- `?([a-z][a-z0-9_]*)`?') { $Matches[1] }
                } | Where-Object { $_ }
                # (Future: map capability id -> MCP tool name; for now, allowed-tools stays generic.)
            }
        }
    }

    $allowedJoined = ($allowed -join ", ")

    $newFront = @"
---
name: $($s.name)
description: $($s.purpose). Generated by scripts/generate-skills.ps1.
allowed-tools: $allowedJoined
shell: $($s.shell)
disable-model-invocation: $($s.disable_model_invocation.ToString().ToLower())
---
"@

    $current = Get-Content $skillFile -Raw

    if ($current -match '^---\r?\n.*?\r?\n---\r?\n') {
        $bodyStart = $current.IndexOf('---', 4) + 3
        # advance past the trailing newline of the second ---
        while ($bodyStart -lt $current.Length -and ($current[$bodyStart] -eq "`r" -or $current[$bodyStart] -eq "`n")) { $bodyStart++ }
        $body = $current.Substring($bodyStart)
    } else {
        $body = $current
    }

    $rewritten = "$newFront`n`n$body"

    if ($DryRun) {
        Write-Host "[dry] $skillFile" -ForegroundColor DarkYellow
    } else {
        Set-Content -Path $skillFile -Value $rewritten -Encoding utf8
        Write-Host "regenerated: $($s.name)" -ForegroundColor Green
    }
}
